#! /bin/bash
# a function to indent c source file with preset styles
declare style=mine
if [[ $1 == "-l" || $1 == "--linux"  ]]
then
    style=linux
elif [[ $i == "-gnu" ]]
then
    style=gnu
fi

for i in $@
do
    if [[ -e $i ]]
    then
        echo $i
        if [[ $style == "mine" ]]
        then
            indent --no-blank-lines-after-declarations \
                    --blank-lines-after-procedures \
                    --braces-on-if-line \
                    --dont-cuddle-else \
                    -ncdw \
                    --braces-on-func-def-line \
                    --braces-on-struct-decl-line \
                    --case-indentation0 \
                    --case-brace-indentation0 \
                    --no-tabs\
                    $i
        elif [[ $style == "linux" ]]
        then
            indent --linux-style $i
        elif [[ $style == "gnu" ]]
        then
            indent -gnu $i
        fi
    fi
done
