#!/usr/bin/env bash
LATEXMK_OPTIONS="-xelatex -pvc"

if [[ $# == 0 ]]
then
    num_tex=$(ls *.tex 2>/dev/null | wc -w)
    if (( num_tex == 0 ))
    then
        echo "No tex file found, exit"
        exit
    elif (( num_tex == 1  ))
    then
        latexmk $LATEXMK_OPTIONS *.tex
    else
        latexmk $LATEXMK_OPTIONS main.tex
    fi
else
    if  [[ -e $1 ]]
    then
        latexmk $LATEXMK_OPTIONS $1
        # laclean $1
    else
        echo "$1 not found, exit"
        exit
    fi
fi
if [[ $? == 0 ]]
then
    latexmk -c
    if (( $(ls *.bbl 2>/dev/null | wc -w) > 0 ))
    then
        rm *.bbl
    fi
    rm *.xdv
    echo "The temp files have been cleared."
else
    echo "Error occurred, temp files saved."
fi
